<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>3.0.0</Version>
    <Authors>Frends</Authors>
	<Copyright>Frends</Copyright>
	<Company>Frends</Company>
	<Product>Frends</Product>
	<PackageTags>Frends</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<Description>Frends task to create Pdf documents.</Description>
	<PackageProjectUrl>https://frends.com/</PackageProjectUrl>
	<RepositoryUrl>https://github.com/FrendsPlatform/Frends.Pdf/</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
	  <AdditionalFiles Include="FrendsTaskMetadata.json" Pack="true" PackagePath="/">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </AdditionalFiles>
      <EmbeddedResource Include="VictorMono-Regular.ttf" Pack="true" PackagePath="/">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="OpenFontSharp" Version="1.0.0" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FrendsTaskAnalyzers" Version="1.*">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
